name: grant-license-checker
description: >-
  Generates a CycloneDX SBOM with license fetching enabled.
inputs:
  sbom_path:
    default: "./sbom.json"
    description: >-
      Path where to store the generated SBOM.
  project_path:
    default: "."
    description: >-
      The path of the project to analyze. Defaults to current working directory.
  ecosystems:
    description: >-
      The project types to support, e.g., `python` or `javascript` (delimited by spaces or newlines).

      List of supported values: https://cyclonedx.github.io/cdxgen/#/PROJECT_TYPES
      ("Project Types" column).

      Default: scan all.
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 26

    - name: Install PNPM
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        corepack install

    - uses: SocketDev/action@ba6de6cc0565af1f42295590380973573297e31f # v1.3.2
      with:
        use-cache: false # reduce risks with poisoned cache
        mode: firewall-free

    - name: Install cdxgen
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        sfw pnpm install

    - name: Generate SBOM
      shell: bash
      env:
        CONF_PROJECT_DIR: "${{ inputs.project_path }}"
        CONF_ECOSYSTEMS: "${{ inputs.ecosystems }}"
        CONF_RESULT_PATH: "${{ inputs.sbom_path }}"
      run: |
        "${GITHUB_ACTION_PATH}/scripts/generate-sbom.sh"
