# Generated by Django 2.2.1 on 2019-06-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("tenants", "0001_initial")]

    operations = [migrations.RemoveField(model_name="tenant", name="name")]
