# Generated by Django 2.2.6 on 2019-11-18 13:01

from django.core.management.utils import get_random_secret_key
from django.db import migrations, models


def assign_random_jwt_secret_keys(apps, _):
    Tenant = apps.get_model("tenants", "Tenant")
    for tenent in Tenant.objects.all():
        tenent.jwt_secret_key = get_random_secret_key()
        tenent.save()


class Migration(migrations.Migration):

    dependencies = [("tenants", "0002_remove_tenant_name")]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="jwt_secret_key",
            field=models.CharField(default=get_random_secret_key, max_length=50),
        ),
        migrations.RunPython(assign_random_jwt_secret_keys, migrations.RunPython.noop),
    ]
