# Generated by Django 3.1.1 on 2020-10-29 11:44

from django.db import migrations, models
import tenants.models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_jwt_secret_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="allowed_client_origins",
            field=models.JSONField(default=tenants.models.default_allowed_client_origins),
        ),
    ]
