# Generated by Django 3.2.4 on 2021-06-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_billing_add_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="orders_hard_limited",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenant",
            name="max_order_count",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
