# Generated by Django 2.2.3 on 2019-07-30 09:36

from django.db import migrations, connection
from tenant_schemas.utils import get_tenant_model


def update_site_domain(apps, _):
    Site = apps.get_model("sites", "Site")
    for site in Site.objects.all():
        tenant = get_tenant_model().objects.get(schema_name=connection.schema_name)
        site.domain = tenant.domain_url
        site.save()


class Migration(migrations.Migration):

    dependencies = [("site", "0002_add_default_data")]

    operations = [migrations.RunPython(update_site_domain, migrations.RunPython.noop)]
