# This workflow only checks the licenses of this repository
# (saleor/saleor-internal-actions).
name: Check Licenses
on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
    paths:
      # Self
      - ".github/workflows/self-check-licenses.yaml"
      - ".github/workflows/run-license-check.yaml"
      - "grant-license-checker/**"
      - "sbom-generator/**"
      # Python Ecosystem
      - "**/pyproject.toml"
      - "**/setup.py"
      - "**/requirements*.txt"
      - "**/Pipfile.lock"
      - "**/poetry.lock"
      # JS/TS Ecosystem
      - "**/package.json"
      - "**/pnpm-lock.yaml"
      - "**/package-lock.json"

jobs:
  default:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/run-license-check.yaml
    with:
      is_same_repository: true

