name: Run tests against grant-license-checker
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - .github/workflows/test-grant-license-checker.yaml
      - ./grant-license-checker/**
  push:
    branches: [main]
    paths:
      - .github/workflows/test-grant-license-checker.yaml
      - ./grant-license-checker/**

permissions: {}

jobs:
  main:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: ./grant-license-checker

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: ./grant-license-checker

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: "./grant-license-checker/pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          # WARNING: remember to bump 'build-system' in ./pyproject.toml when changing
          #          the uv version
          version: "0.11.3"
          working-directory: ./grant-license-checker
          activate-environment: true
          # hash for 'uv-x86_64-unknown-linux-gnu.tar.gz'
          # (from https://github.com/astral-sh/uv/releases)
          checksum: "c0f3236f146e55472663cfbcc9be3042a9f1092275bbe3fe2a56a6cbfd3da5ce"

      - name: Install Python Dependencies
        run: |
          uv sync --locked --no-editable --link-mode=copy --no-dev

      - name: pytest
        run: |
          uv run pytest ./
